n = input('Digite qualquer coisa:')
print('O tipo primitivo dessa variavel é:',type(n))
print('É alfanumerico?',n.isalnum())
print('É alfabético?',n.isalpha())
print('É numérico?',n.isnumeric())
print('É decimal?',n.isdecimal())
print('Só tem espaços?',n.isspace())
print('Está em maiusculas?',n.isupper())
print('Esta em minuscula',n.islower())
print('Esta capitalizada(Maiusculo e minusculo)', n.istitle())
